# Generated by Django 4.2.7 on 2025-10-04 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends Only"),
                    ("private", "Private"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_watch_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
