version: '3.8'

services:
  # Django Development Server
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=movie_recommendation_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=movie_recommendation_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # Celery Worker (Development)
  celery:
    build:
      context: .
      target: development
    command: celery -A movie_recommendation worker --loglevel=debug
    environment:
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=movie_recommendation_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - db
      - redis

volumes:
  postgres_dev_data:
  redis_dev_data:
