services:
  - type: web
    name: movie-recommendation
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn movie_recommendation.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: TMDB_API_KEY
        value: your-tmdb-api-key-here

databases:
  - name: movie-db
    plan: free