# Generated by Django 4.2.7 on 2025-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["popularity"], name="movies_popular_befb0b_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["vote_average"], name="movies_vote_av_b71f90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_release_e1d0b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["tmdb_id"], name="movies_tmdb_id_472987_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["genre_ids"], name="movies_genre_i_47f983_idx"),
        ),
    ]
