# Generated by Django 4.2.7 on 2025-10-01 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User-specific cache (null for general cache)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for general recommendations (trending, popular)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='user_intera_user_id_5f7a30_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['movie', 'interaction_type'], name='user_intera_movie_i_1118af_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['created_at'], name='user_intera_created_712f51_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcache',
            index=models.Index(fields=['cache_type', 'expires_at'], name='recommendat_cache_t_5b879e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcache',
            index=models.Index(fields=['user', 'cache_type'], name='recommendat_user_id_d43dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='recommendat_user_id_373e78_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['recommendation_type', 'created_at'], name='recommendat_recomme_d8dde6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'movie', 'recommendation_type')},
        ),
    ]
